server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.42.29.134:3306/personal_website?serverTimezone=GMT-8
    username: root
    password: Tapebook123#
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

    jpa:
      h2:
        console:
          enabled: true
          path: /h2-console
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true

app:
  file:
#    storage-location: /Users/yuwen/Downloads/notescover
    storage-location: /home/azureuser/notescover